title: German practice materials
description: Practical German practice files (present, perfekt, prepositions, verbs)
baseurl: "/german"
url: "https://hamednourhani.github.io"
markdown: kramdown
theme: null
plugins: []
